---
image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      poetry install --with dev
      poetry run pytest --composition_chain_size=0 --iteration_size=0

github:
  prebuilds:
    addComment: true
...
